#DISABLED UNTIL CODECOMMIT SUPPORTS YARN2 NATIVELY: https://issues.amazon.com/issues/GHWK-17176
#yarnPath: ".yarn/releases/yarn-berry.cjs"

npmRegistryServer: "https://template-194755611428.d.codeartifact.us-west-2.amazonaws.com/npm/global-templates/"
